name: CI

on:
  push: {}
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    container: python:3.12-slim
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v0.0.26

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: installation, env setup and test running
        run:
          uv run pytest -v
