name: CI

on:
  push: {}
  pull_request:
    branches: ["main", "master"]

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1

  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: python:3.12-slim
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies and run tests
        run: |
          uv pip install -e ".[dev]"
          pytest -v
        env:
          PYTHONPATH: ${{ github.workspace }}
