name: CI

on:
  push: {}
  pull_request:
    branches: ["main", "master"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Create and activate virtual environment
        run: |
          uv venv .venv
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          . .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Run Ruff
        run: |
          . .venv/bin/activate
          ruff check .

      - name: Run pytest
        run: |
          . .venv/bin/activate
          pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
